WORKING_FOLDER = "MovieTestingSet"

YOLO_OBJECT_COMPARISSON = False
MASK_OBJECT_COMPARISSON = False
FACE_COLOUR_COMPARISSON = True
CLOTHING_COLOUR_COMPARISSON = True

DRAW_DISPLAY_IMAGES = True
DRAW_MASK_RESULTS = True
DRAW_FACE_RESULTS = True
DRAW_POSE_RESULTS = True

# Configuration for Mask R-CNN component
MASK_CONFIDENCE = 0.6
MASK_THRESHOLD = 0.5
MASK_WEIGHTS = "frozen_inference_graph.pb"
MASK_CONFIG = "mask_rcnn_inception_v2_coco_2018_01_28.pbtxt"
MASK_LABELS = "object_detection_classes_coco.txt"

#YOLO Component configuration
YOLO_THRESHOLD = 0.9

# Configuration for the Pose Detection component

# Switch pose detection to use config in here
POSE_WEIGHTS = "pose_deploy_linevec.prototxt"
POSE_CONFIG = "pose_iter_440000.caffemodel"

# Available types are Cascade and dlib
FACE_DETECTION_TYPE = "dlib"
FACE_SHADOW_REMOVAL = True
FACE_SHADOW_REMOVAL_TYPE = "automatedMSRCR"

AVERAGE_FACE_COLOUR_DRIFT = 20
FACE_COLOUR_DRIFT_STAGES = 5

MASK_AVERAGE_FACE_COLOUR_DRIFT = 20
MASK_FACE_COLOUR_DRIFT_STAGES = 5

HSV_FACE_COLOUR_DRIFT = 20
HSV_FACE_COLOUR_DRIFT_STAGES = 5

MASK_HSV_FACE_COLOUR_DRIFT = 20
MASK_HSV_FACE_COLOUR_DRIFT_STAGES = 5

POSE_DETECTION_THRESHOLD = 0.1
POSE_DETECTION_RADIUS = 2

AVERAGE_POSE_COLOUR_DRIFT = 50
POSE_COLOUR_DRIFT_STAGES = 5

HSV_POSE_COLOUR_DRIFT_STAGES = 20
POSE_HSV_DRIFT_STAGES = 5
